In [9]:
import numpy as np

# Operações com matrizes

In [10]:
a = np.array([[1, 2, 3],[2, 1, -1]])
a

array([[ 1,  2,  3],
       [ 2,  1, -1]])

In [13]:
b = np.array([[-2, 0, 1],[3, 0, 1]])
b

array([[-2,  0,  1],
       [ 3,  0,  1]])

In [22]:
c = np.array([[-1],[2],[4]])
c

array([[-1],
       [ 2],
       [ 4]])

In [26]:
d = np.array([2, -1])
d

array([ 2, -1])

### 1.a: A + B

In [32]:
a+b

array([[-1,  2,  4],
       [ 5,  1,  0]])

### 1.b: A.C

In [31]:
a.dot(c)

array([[15],
       [-4]])

### 1.c: B.C

In [33]:
b.dot(c)

array([[6],
       [1]])

### 1.d: D.A

In [34]:
d.dot(a)

array([0, 3, 7])

### 1.f: D.B

In [36]:
d.dot(b)

array([-7,  0,  1])

### 1.g: -A

In [37]:
-a

array([[-1, -2, -3],
       [-2, -1,  1]])

### 1.h: A.C

In [39]:
-d

array([-2,  1])