In [2]:
import numpy as np

# Operações com matrizes


#### Exercícios das páginas 11, 12 e 13

In [3]:
a = np.array([[1, 2, 3],[2, 1, -1]])
a

array([[ 1,  2,  3],
       [ 2,  1, -1]])

In [13]:
b = np.array([[-2, 0, 1],[3, 0, 1]])
b

array([[-2,  0,  1],
       [ 3,  0,  1]])

In [22]:
c = np.array([[-1],[2],[4]])
c

array([[-1],
       [ 2],
       [ 4]])

In [26]:
d = np.array([2, -1])
d

array([ 2, -1])

### 1.a: A + B

In [32]:
a+b

array([[-1,  2,  4],
       [ 5,  1,  0]])

### 1.b: A.C

In [31]:
a.dot(c)

array([[15],
       [-4]])

### 1.c: B.C

In [33]:
b.dot(c)

array([[6],
       [1]])

### 1.d: D.A

In [34]:
d.dot(a)

array([0, 3, 7])

### 1.f: D.B

In [36]:
d.dot(b)

array([-7,  0,  1])

### 1.g: -A

In [37]:
-a

array([[-1, -2, -3],
       [-2, -1,  1]])

### 1.h: A.C

In [39]:
-d

array([-2,  1])

### 2.Seja A = [[ 2 x**2], [2x-1  0]]. Se A.t = A, entao x ? ------- R: 1


In [120]:
a = np.array([[2, 1**2], [2*1-1, 0]])

In [153]:
print('A:')
print(a)

print('\nA.t:')
print(a.transpose())

A:
[[ 2 -3 -5]
 [-1  4  5]
 [ 1 -3 -4]]

A.t:
[[ 2 -1  1]
 [-3  4 -3]
 [-5  5 -4]]


### 3. Se A é uma matriz simétrica, então A-A.t= ????? --------- R: Matriz Nula

In [117]:
a = np.array([[4, 3, -1], [3, 2 ,0], [-1, 0, 5]])
a_t = a.transpose() #transposta de a

In [152]:
print('A:')
print(a)

print('\nA.t:')
print(a_t)

print('\nA-A:')
print(a-a)

A:
[[ 2 -3 -5]
 [-1  4  5]
 [ 1 -3 -4]]

A.t:
[[ 4  3 -1]
 [ 3  2  0]
 [-1  0  5]]

A-A:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


### 4. Se A é uma matriz triangular superior, então A.t = ? ----------- R: Matriz triangular inferior

In [114]:
a = np.array([[4, 2, 1], [0, 2, 3], [0, 0, 5]])

In [115]:
print('A:')
print(a)

print('\nA.t:')
print(a.transpose())

A:
[[4 2 1]
 [0 2 3]
 [0 0 5]]

A.t:
[[4 0 0]
 [2 2 0]
 [1 3 5]]


### 5. Se A é uma matriz diagonal, então A.t=?  ------------------ R: A.t = A

In [112]:
a = np.zeros((4,4), int)
np.fill_diagonal(a,3)

In [113]:
print('A:')
print(a)

print('\nA.t:')
print(a.transpose())

A:
[[3 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 3]]

A.t:
[[3 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 3]]


### 6. Verdadeiro ou Falso:
<h3> a) (-A).t = -(A.t) </h3>

In [110]:
a = np.array([[1, -3, 2], [2, 1, -3], [4, -3, -1]])

In [151]:
print('A:')
print(a)

print('\n-(A).t: \n{}\n'.format((-a).transpose()))
print('\n-(A.t): \n{}\n'.format(-(a.transpose())))

print(np.array_equal(b,c))

A:
[[ 2 -3 -5]
 [-1  4  5]
 [ 1 -3 -4]]

-(A).t: 
[[-2  1 -1]
 [ 3 -4  3]
 [ 5 -5  4]]


-(A.t): 
[[-2  1 -1]
 [ 3 -4  3]
 [ 5 -5  4]]

False


### b) (A+B.t) = B.t + A.t

In [67]:
a = np.array([[2, -3, -5], [-1, 4, 5], [1, -3, -4]])
b = np.array([[-1, 3, 5], [1, -3, -5], [-1, 3, 5]])

In [150]:
print('A:')
print(a)
print('B:')
print(b)

print('\n(A+B.t):')
print((a+b).transpose())

print('\nB.t + A.t:')
print((b.transpose()) + (a.transpose()))

print('\n')
print(np.array_equal((a+b).transpose(), ((b.transpose()) + (a.transpose()))))

A:
[[ 2 -3 -5]
 [-1  4  5]
 [ 1 -3 -4]]
B:
[[-1  3  5]
 [ 1 -3 -5]
 [-1  3  5]]

(A+B.t):
[[1 0 0]
 [0 1 0]
 [0 0 1]]

B.t + A.t:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


True


### c) Se A.B = 0, então A=0 ou B=0

In [108]:
True

True

### d) (k1.A).(k2.B) = (k1.k2).A.B

In [154]:
k1 = 2
k2 = 3
a = np.array([[2, -3, -5], [-1, 4, 5], [1, -3, -4]])
b = np.array([[-1, 3, 5], [1, -3, -5], [-1, 3, 5]])

In [178]:
print('A: \n {}'.format(a))
print('B: \n {}\n'.format(b))

print('(k1.A).(k2.B): \n{}\n'.format(np.dot((k1*a),(k2*b))))
print('(k1.k2).A.B: \n{}\n'.format((k1*k2)*np.dot(a,b)))

print(np.array_equal(np.dot((k1*a),(k2*b)), (k1*k2)*np.dot(a,b)))

A: 
 [[-2  2  4]
 [ 1 -3 -4]
 [-1  2  3]]
B: 
 [[-1  3 -2]
 [-2 -1  3]
 [-4  3  1]]

(k1.A).(k2.B): 
[[-108   24   84]
 [ 126  -36  -90]
 [ -90   24   66]]

(k1.k2).A.B: 
[[-108   24   84]
 [ 126  -36  -90]
 [ -90   24   66]]

True


### e) (-A).(-B) = -(A.B)

In [161]:
a = np.array([[-2, 2, 4], [1, -3, -4], [-1, 2, 3]])
b = np.array([[-1, 3, -2], [-2, -1, 3], [-4, 3, 1]])

In [182]:
print('A: \n {}'.format(a))
print('B: \n {}\n'.format(b))

print('(-A).(-B) : \n{}\n'.format(np.dot(-a,-b)))

print('-(A.B): \n{}\n'.format(-(np.dot(a,b))))

print(np.array_equal(np.dot(-a,-b), -(np.dot(a,b))))

A: 
 [[-2  2  4]
 [ 1 -3 -4]
 [-1  2  3]]
B: 
 [[-1  3 -2]
 [-2 -1  3]
 [-4  3  1]]

(-A).(-B) : 
[[-18   4  14]
 [ 21  -6 -15]
 [-15   4  11]]

-(A.B): 
[[ 18  -4 -14]
 [-21   6  15]
 [ 15  -4 -11]]

False


### f) Se A e B são matrizes simétricas, então A.B = B.A

In [183]:
False

False

### g) Se A.B = 0 então B.A = 0

In [184]:
False

False

### h) Se podemos efeturar o produto A.A então A é uma matriz quadrada

In [185]:
True

True